### ISSUE TITLE
Cannot run tensorboard on windows 

### ISSUE THREAD

**Issue by gungui98** [UETAILab/uetai#13]
**Describe the bug**
The name is not correct so that it cannot be run on windows

**To Reproduce**
4. See errors

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11, Ubuntu 18.04]
 - Version [e.g. v1]

**Additional context**

**Comment by manhdung20112000** [comment]
This happens due to the limited of Windows OS function calls that handle filenames. Some characters might not be allowed in a folder name when `tensorboard` init its log directory. 

Thanks for raise the issue. It'll be fixed in the next update

**Comment by manhdung20112000** [comment]
Fixed in #16
