### ISSUE TITLE
Error when import: name 'Artifact' is not defined

### ISSUE THREAD

**Issue by CaoHoangTung** [UETAILab/uetai#14]
**Describe the bug**
Fail to use the library

**To Reproduce**
pip install git+https://github.com/UETAILab/uetai
`import uetai`

**Expected behavior**
The module is used successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/22815550/134764159-ce94dbe5-6406-4720-b84a-548f914e3a78.png)

**Comment by manhdung20112000** [comment]
It'll be remove soon

**Comment by manhdung20112000** [comment]
Fixed in #16
