### ISSUE TITLE
Add file upload CLI after training

### ISSUE THREAD

**Issue by manhdung20112000** [UETAILab/uetai#3]
There is a need to gather artifact and send it into wandb server after training, consider implement that feature.

The module would implement `logger.save(path, object` and write a temporary file.
by call `uetai upload file_list.txt`, the module should upload every files in `file_list.txt` and upload that into wandb with same experiment.

**Comment by gungui98** [comment]
How to test this feature

```python
logger = SummaryWriter("experiment")
logger.save("model.pth", model)
```
test code
```python
# in remote wandb we have "experiment/model.pth"
.....
```
